### ISSUE TITLE
Cannot replace just hit or miss sounds

### ISSUE THREAD

**Issue by ChrisJAllan** [SamuelTulach/SoundReplacer#1]
Turning the hit sound off works correctly, but setting a custom sound for only hit or miss plays the default one. Setting both works correctly.

**Comment by SamuelTulach** [comment]
![image](https://user-images.githubusercontent.com/16323119/141642660-5936ed10-21c2-43fd-947b-b7993e7d04ec.png)

Haven't noticed that I made it wrong while copy-pasting. Should be working in next release.

**Comment by SamuelTulach** [comment]
Please try [the new release](https://github.com/SamuelTulach/SoundReplacer/releases/tag/0.0.4). If the issue persist, please reopen the issue.
